---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/yoteschat.tech/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp chat.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp users.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH